// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var DbManager = require("../dbManager.bs.js");
var GraphqlRelay = require("graphql-relay");

async function toDb(id, _b) {
  var idMapped = GraphqlRelay.fromGlobalId(id);
  var match = idMapped.type;
  if (match === "User") {
    return await DbManager.findUser({
                id: idMapped.id
              });
  } else {
    return null;
  }
}

function objToType(obj) {
  var isUser = obj.email;
  if (isUser !== null) {
    return "User";
  } else {
    return null;
  }
}

var nodeDefinitions = GraphqlRelay.nodeDefinitions(toDb, objToType);

exports.toDb = toDb;
exports.objToType = objToType;
exports.nodeDefinitions = nodeDefinitions;
/* nodeDefinitions Not a pure module */
