// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Relay = require("../external/relay.bs.js");
var DbManager = require("../dbManager.bs.js");
var GraphqlRelay = require("graphql-relay");

async function toDb(id, _b) {
  var match = Relay.parseCustomIdType(id);
  if (match !== undefined && match[0] === "user") {
    return await DbManager.findUser({
                id: match[1]
              });
  } else {
    return null;
  }
}

function objToType(obj) {
  var isUser = obj.email;
  if (isUser !== null) {
    return "User";
  } else {
    return null;
  }
}

var nodeDefinitions = GraphqlRelay.nodeDefinitions(toDb, objToType);

exports.toDb = toDb;
exports.objToType = objToType;
exports.nodeDefinitions = nodeDefinitions;
/* nodeDefinitions Not a pure module */
