// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var GraphqlRelay = require("graphql-relay");

var newConnctionArgsFun = ((connectionArgs) => ({...connectionArgs}));

function newConnectionArgs(param) {
  return newConnctionArgsFun(GraphqlRelay.connectionArgs);
}

exports.newConnctionArgsFun = newConnctionArgsFun;
exports.newConnectionArgs = newConnectionArgs;
/* graphql-relay Not a pure module */
