// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Relay = require("../external/relay.bs.js");
var Graphql = require("graphql");
var NodeDefinition = require("./nodeDefinition.bs.js");

var userType = new Graphql.GraphQLObjectType({
      name: "User",
      description: "A user in the system.",
      interfaces: (function (param) {
          return [NodeDefinition.nodeDefinitions.nodeInterface];
        }),
      fields: (function (param) {
          return {
                  id: {
                    type: new Graphql.GraphQLNonNull(Graphql.GraphQLID),
                    description: "The uuid of the user.",
                    resolve: (function (obj) {
                        return Relay.customIdTypeCreator(obj, "user");
                      })
                  },
                  name: {
                    type: Graphql.GraphQLString,
                    description: "The name of the user.",
                    resolve: undefined
                  },
                  email: {
                    type: Graphql.GraphQLString,
                    description: "The email of the user.",
                    resolve: undefined
                  },
                  createdAt: {
                    type: Graphql.GraphQLFloat,
                    description: "The date the user was created.",
                    resolve: undefined
                  },
                  updatedAt: {
                    type: Graphql.GraphQLFloat,
                    description: "The date the user was last updated.",
                    resolve: undefined
                  }
                };
        })
    });

exports.userType = userType;
/* userType Not a pure module */
