// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var InitPrisma = require("./initPrisma.bs.js");

async function findUser(id) {
  return await InitPrisma.prisma.user.findUnique({
              where: id
            });
}

async function getUsers(param) {
  return await InitPrisma.prisma.user.findMany();
}

async function getConfigs(param) {
  return await InitPrisma.prisma.config.findMany();
}

exports.findUser = findUser;
exports.getUsers = getUsers;
exports.getConfigs = getConfigs;
/* InitPrisma Not a pure module */
