// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var jsUnwrapVariant = (function unwrapVariant(v) {
  if (v._0 !== undefined) {
    return v._0;
  } else {
    return v;
  }
});

var jsFakeUnwrapVariant = (function unwrapVariant(v) {
  return v;
});

exports.jsUnwrapVariant = jsUnwrapVariant;
exports.jsFakeUnwrapVariant = jsFakeUnwrapVariant;
/* No side effect */
