// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Client = require("@prisma/client");

var prisma = new Client.PrismaClient();

exports.prisma = prisma;
/* prisma Not a pure module */
